server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

store-api:
  baseUrl: http://localhost/9091
  storeSearchUrl: /store/search?

